---
name: Deploy Website with Surge

on:
  push:
    branches:
      - master
  
jobs:
  build:
    name: Job_Deploy_Surge
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: action/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Setup Surge
        run: npm install --global surge
      - name: Execute Deployment with Surge
        run: surge ./ project001-20_ayeshaghani.surge.sh --token ${{ secrets.project001_20_surge_token }}  


...
